(executable
 (name test_e2e)
 (modules test_e2e)
 (libraries
  demo_events
  eio
  eio_main
  eio.unix
  obs-eio
  sol_obs
  kafka_eio_service
  sol_cli
  sol_svc
  sol_worker
  sol_jobs
  sol_outbox
  pg-eio
  caqti
  caqti-eio
  caqti-eio.unix
  caqti-driver-postgresql
  unix
  yojson
  windtrap))

(rule
 (alias runtest)
 (deps
  (source_tree ../migrations))
 (action
  (setenv
   KAFKA_SECURITY_PROTOCOL
   "plaintext"
   (setenv
    KAFKA_BROKERS
    "localhost:9092"
    (setenv
     SCHEMA_REGISTRY_URL
     "http://localhost:8081"
     (setenv
      REDPANDA_ADMIN_URL
      "http://localhost:9644"
      (setenv
       LOKI_URL
       "http://localhost:3100"
       (setenv
        POSTGRES_URL
        "postgresql://postgres:dev@localhost:5432/sol_dev"
        (run ./test_e2e.exe)))))))))

(alias
 (name ci-e2e)
 (deps
  (alias_rec runtest)))
