(library
 (name sol_svc)
 (public_name sol-svc)
 (wrapped false)
 (modules
  auth_cache
  auth_internal
  peer
  request
  response
  route
  route_internal
  service)
 (private_modules auth_cache auth_internal route_internal)
 (libraries
  cohttp-eio
  http
  uri
  yojson
  base64
  eio
  eio.unix
  obs-eio
  sol_obs
  jose
  ptime
  https-eio
  sol-svc-core
  sol_runtime))
