(library
 (name kafka_test_helpers)
 (modules kafka_test_brokers kafka_test_helpers))

(test
 (name test_kafka_service)
 (modules test_kafka_service)
 (libraries kafka_eio_service sol_runtime kafka-eio windtrap yojson uri unix))

(test
 (name test_declared_ca)
 (modules test_declared_ca)
 (libraries
  kafka_eio_service
  eio_main
  tls-eio
  x509
  mirage-crypto-rng.unix
  windtrap
  yojson
  unix)
 (deps
  (source_tree fixtures)))

(executable
 (name test_kafka_service_integration)
 (modules test_kafka_service_integration)
 (libraries
  kafka_eio_service
  sol_worker
  kafka-eio
  kafka_test_helpers
  windtrap
  eio_main
  unix))

(rule
 (alias runtest-integration)
 (action
  (setenv
   KAFKA_SECURITY_PROTOCOL
   "plaintext"
   (setenv
    KAFKA_BROKERS
    "localhost:9092"
    (setenv
     SCHEMA_REGISTRY_URL
     "http://localhost:8081"
     (setenv
      REDPANDA_ADMIN_URL
      "http://localhost:9644"
      (run ./test_kafka_service_integration.exe)))))))

(alias
 (name ci-unit)
 (deps
  (alias_rec runtest)))

(alias
 (name ci-integration-kafka)
 (deps
  (alias_rec runtest-integration)))
