(* Schema compatibility gate (FULL) — generated by sol new workspace.
   Run it against the registry that holds your published schemas:
     SCHEMA_REGISTRY_URL=http://... dune exec ./test/test_schemas.exe
   (It is an executable, not a dune test: `dune test` does not run it.)
   List EVERY event MESSAGE module this workspace publishes below: a message that
   is not listed is not checked.
   Without SCHEMA_REGISTRY_URL the check is skipped on a developer machine, but
   under CI (CI is set) it fails: a gate that passes because it did not run is
   not a gate. *)
let () =
  let under_ci =
    match Sys.getenv_opt "CI" with
    | None | Some ("" | "0" | "false") -> false
    | Some _ -> true
  in
  match Sys.getenv_opt "SCHEMA_REGISTRY_URL" with
  | None | Some "" when under_ci ->
    Printf.eprintf
      "schema compatibility NOT CHECKED: SCHEMA_REGISTRY_URL is not set under CI\n%!";
    exit 1
  | None | Some "" ->
    Printf.printf "SCHEMA_REGISTRY_URL not set — skipping schema compat check\n%!"
  | Some registry_url ->
    Eio_main.run (fun env ->
      match Kafka_service.Schema.check_all
              ~net:env#net
              ~clock:env#clock
              ~registry_url
              [ (module Charged) ]
      with
      | Ok () ->
        Printf.printf "schema compatibility: ok\n%!"
      | Error e ->
        Printf.eprintf "schema compatibility FAILED: %s\n%!" (Kafka_service.error_to_string e);
        exit 1
    )
