#!/usr/bin/env bash
# HARDEN-002 (run 1): the production Postgres path must never send an empty master
# password to AWS. Sol refuses one earlier (test_db_credential), but the provider
# module must also fail on its own, because terraform can be driven directly.
#
# This is deliberately offline: it guards the module-side precondition
# structurally (no terraform, no AWS), and additionally runs `terraform fmt
# -check` when terraform happens to be installed -- `fmt` parses the HCL, so it
# catches syntax breakage without `init`, providers or credentials.
set -euo pipefail

root="$1"
aws="$root/cli/platform/infra/aws/main.tf"

if [ ! -f "$aws" ]; then
  echo "FAIL: $aws is missing" >&2
  exit 1
fi

rds_block="$(awk '/^resource "aws_db_instance" "postgres"/,/^}/' "$aws")"

if [ -z "$rds_block" ]; then
  echo "FAIL: aws_db_instance.postgres not found in $aws" >&2
  exit 1
fi

case "$rds_block" in
  *precondition*) : ;;
  *)
    echo "FAIL: aws_db_instance.postgres has no precondition guarding db_password;" >&2
    echo "      an empty password would again reach CreateDBInstance." >&2
    exit 1
    ;;
esac

case "$rds_block" in
  *db_password*) : ;;
  *)
    echo "FAIL: the RDS precondition no longer mentions db_password" >&2
    exit 1
    ;;
esac

case "$rds_block" in
  *multi_az*) : ;;
  *)
    echo "FAIL: aws_db_instance.postgres lost its multi_az wiring" >&2
    exit 1
    ;;
esac

# HARDEN-002 run 2, finding 9: the public destroy lifecycle must be completable.
# A protected RDS instance needs its protection lifted for the destroy, and the
# final snapshot it takes needs a unique name -- generated by the destroy path, not
# invented by the operator.
#
# These assert the three wires themselves, not merely that the names still appear
# somewhere: a check that only greps for `rds_skip_final_snapshot` passes happily
# while its default flips to true and production destruction goes silent.
vars_tf="$root/cli/platform/infra/aws/variables.tf"

variable_default() {
  awk -v want="variable \"$1\" {" '
    index($0, want) == 1 { inside = 1; next }
    inside && /^}/ { exit }
    inside && $1 == "default" { print $3; exit }
  ' "$vars_tf"
}

if [ "$(variable_default rds_deletion_protection)" != "true" ]; then
  echo "FAIL: rds_deletion_protection no longer defaults to true;" >&2
  echo "      a production database would be destroyable by an ordinary apply." >&2
  exit 1
fi

if [ "$(variable_default rds_skip_final_snapshot)" != "false" ]; then
  echo "FAIL: rds_skip_final_snapshot no longer defaults to false;" >&2
  echo "      destroying production Postgres would take no final snapshot." >&2
  exit 1
fi

# Comments stripped: the block explains finding 9 in prose directly above these
# assignments, so a match against the raw text would be satisfied by the comment
# that survives the very deletion this is guarding against.
rds_code="$(printf '%s\n' "$rds_block" | sed 's/#.*//')"

case "$rds_code" in
  *"skip_final_snapshot = var.rds_skip_final_snapshot"*) : ;;
  *)
    echo "FAIL: aws_db_instance.postgres no longer takes skip_final_snapshot from its own" >&2
    echo "      variable; finding 9 was that this was derived from deletion protection." >&2
    exit 1
    ;;
esac

case "$rds_code" in
  *"final_snapshot_identifier = "*) : ;;
  *)
    echo "FAIL: aws_db_instance.postgres sets no final_snapshot_identifier, so terraform" >&2
    echo "      refuses to destroy it at all whenever a final snapshot is required." >&2
    exit 1
    ;;
esac
if ! grep -q 'rds_deletion_protection=false' "$root/cli/sol/bin/cmd_cloud_tf.ml"; then
  echo "FAIL: sol cloud destroy no longer lifts deletion protection, so it cannot finish against a protected target" >&2
  exit 1
fi
if ! grep -q 'rds_final_snapshot_identifier=' "$root/cli/sol/bin/cmd_cloud_tf.ml"; then
  echo "FAIL: sol cloud destroy no longer names the final snapshot uniquely" >&2
  exit 1
fi

if command -v terraform >/dev/null 2>&1; then
  terraform fmt -check -recursive "$root/cli/platform/infra" >/dev/null
  echo "production infra: precondition present, terraform fmt ok"
else
  echo "production infra: precondition present (terraform not installed, skipped fmt)"
fi
